/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as UploadTemplateIdRouteImport } from './routes/upload.$templateId'
import { Route as MappingTemplateIdUploadIdRouteImport } from './routes/mapping.$templateId.$uploadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadTemplateIdRoute = UploadTemplateIdRouteImport.update({
  id: '/upload/$templateId',
  path: '/upload/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingTemplateIdUploadIdRoute =
  MappingTemplateIdUploadIdRouteImport.update({
    id: '/mapping/$templateId/$uploadId',
    path: '/mapping/$templateId/$uploadId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRoute
  '/upload/$templateId': typeof UploadTemplateIdRoute
  '/mapping/$templateId/$uploadId': typeof MappingTemplateIdUploadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRoute
  '/upload/$templateId': typeof UploadTemplateIdRoute
  '/mapping/$templateId/$uploadId': typeof MappingTemplateIdUploadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRoute
  '/upload/$templateId': typeof UploadTemplateIdRoute
  '/mapping/$templateId/$uploadId': typeof MappingTemplateIdUploadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/templates'
    | '/upload/$templateId'
    | '/mapping/$templateId/$uploadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/templates'
    | '/upload/$templateId'
    | '/mapping/$templateId/$uploadId'
  id:
    | '__root__'
    | '/'
    | '/templates'
    | '/upload/$templateId'
    | '/mapping/$templateId/$uploadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplatesRoute: typeof TemplatesRoute
  UploadTemplateIdRoute: typeof UploadTemplateIdRoute
  MappingTemplateIdUploadIdRoute: typeof MappingTemplateIdUploadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$templateId': {
      id: '/upload/$templateId'
      path: '/upload/$templateId'
      fullPath: '/upload/$templateId'
      preLoaderRoute: typeof UploadTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping/$templateId/$uploadId': {
      id: '/mapping/$templateId/$uploadId'
      path: '/mapping/$templateId/$uploadId'
      fullPath: '/mapping/$templateId/$uploadId'
      preLoaderRoute: typeof MappingTemplateIdUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplatesRoute: TemplatesRoute,
  UploadTemplateIdRoute: UploadTemplateIdRoute,
  MappingTemplateIdUploadIdRoute: MappingTemplateIdUploadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
